#ifndef OpenVision_HPP
#define OpenVision_HPP
#include <jni.h>
#include "ImgApp/GesturePoint.hpp"
#include "ImgApp/UniStrokeGestureRecognizer.hpp"


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openvision_androidgesture_CreateGestureActivity */


#ifdef __cplusplus
extern "C" {
#endif
#undef com_openvision_androidgesture_CreateGestureActivity_LENGTH_THRESHOLD
#define com_openvision_androidgesture_CreateGestureActivity_LENGTH_THRESHOLD 120.0f
/*
 * Class:     com_openvision_androidgesture_CreateGestureActivity
 * Method:    addGesture
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openvision_androidgesture_GestureLibraryInterface_addGesture(JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     com_openvision_androidgesture_CreateGestureActivity
 * Method:    setDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openvision_androidgesture_GestureLibraryInterface_setDirectory(JNIEnv *, jobject, jstring);





/**
 * @brief method to return a float value from jobject
 * @param env JNI Environment points
 * @param jobject input argument to the function
 *
 * @return out is variable of type float
 */
float getFloat(JNIEnv *env,jobject value);

/**
 * @brief method to return a long value from jobject
 * @param env JNI Environment points
 * @param jobject input argument to the function
 *
 * @return out is variable of type long
 */
long getLong(JNIEnv *env,jobject value);
#ifdef __cplusplus
}
#endif
#endif
