/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_openvision_androidgesture_CreateGestureActivity */

#ifndef _Included_com_openvision_androidgesture_CreateGestureActivity
#define _Included_com_openvision_androidgesture_CreateGestureActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_openvision_androidgesture_CreateGestureActivity_LENGTH_THRESHOLD
#define com_openvision_androidgesture_CreateGestureActivity_LENGTH_THRESHOLD 120.0f
/*
 * Class:     com_openvision_androidgesture_CreateGestureActivity
 * Method:    addGesture
 * Signature: (Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openvision_androidgesture_CreateGestureActivity_addGesture
  (JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     com_openvision_androidgesture_CreateGestureActivity
 * Method:    setDirectory
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_openvision_androidgesture_CreateGestureActivity_setDirectory
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
