
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xf6\xc2\x99\xb6s\xc2{\xdf\x82\x8e\xcd\xb5\x87\xab\x95\xfe'
    
_lr_action_items = {'LBRACKET':([2,],[4,]),'text':([0,],[1,]),'NUMBER':([0,4,],[2,5,]),'$end':([1,2,3,5,],[-2,-1,0,-3,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'factor':([0,],[3,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> factor","S'",1,None,None,None),
  ('factor -> NUMBER','factor',1,'p_num','/home/prasad/repository/OpenVision/OpenVision/ImgML/PyVision/test_parser2.py',7),
  ('factor -> text','factor',1,'p_all','/home/prasad/repository/OpenVision/OpenVision/ImgML/PyVision/test_parser2.py',17),
  ('factor -> NUMBER LBRACKET NUMBER','factor',3,'p_LBRACKET','/home/prasad/repository/OpenVision/OpenVision/ImgML/PyVision/test_parser2.py',21),
]
