.TH "jni/ImgApp/ Directory Reference" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/ImgApp/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGesturePoint\&.cpp\fP"
.br
.ti -1c
.RI "file \fBGesturePoint\&.hpp\fP"
.br
.ti -1c
.RI "file \fBUniStrokeGesture\&.cpp\fP"
.br
.ti -1c
.RI "file \fBUniStrokeGesture\&.hpp\fP"
.br
.ti -1c
.RI "file \fBUniStrokeGestureRecognizer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBUniStrokeGestureRecognizer\&.hpp\fP"
.br
.in -1c
