.TH "gen/com/openvision/androidgesture/ Directory Reference" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gen/com/openvision/androidgesture/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBuildConfig\&.java\fP"
.br
.ti -1c
.RI "file \fBR\&.java\fP"
.br
.in -1c
