.TH "jni/ Directory Reference" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBCommon\fP"
.br
.ti -1c
.RI "directory \fBImgApp\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBOpenVision\&.cpp\fP"
.br
.in -1c
