.TH "obj/local/ Directory Reference" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj/local/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBarmeabi\fP"
.br
.ti -1c
.RI "directory \fBarmeabi-v7a\fP"
.br
.in -1c
