.TH "obj/local/armeabi/objs/OpenVision/ImgApp/ Directory Reference" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj/local/armeabi/objs/OpenVision/ImgApp/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGesturePoint\&.o\&.d\fP"
.br
.ti -1c
.RI "file \fBUniStrokeGesture\&.o\&.d\fP"
.br
.ti -1c
.RI "file \fBUniStrokeGestureRecognizer\&.o\&.d\fP"
.br
.in -1c
