.TH "com.openvision.androidgesture.BuildConfig" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.openvision.androidgesture.BuildConfig \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final boolean \fBDEBUG\fP = true"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "final boolean \fBcom\&.openvision\&.androidgesture\&.BuildConfig\&.DEBUG\fP = true\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
