.TH "com::openvision" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com::openvision \- 
.SH SYNOPSIS
.br
.PP
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBandroidgesture\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
