.TH "com.openvision.androidgesture.R" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.openvision.androidgesture.R \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBattr\fP"
.br
.ti -1c
.RI "class \fBcolor\fP"
.br
.ti -1c
.RI "class \fBdimen\fP"
.br
.ti -1c
.RI "class \fBdrawable\fP"
.br
.ti -1c
.RI "class \fBid\fP"
.br
.ti -1c
.RI "class \fBlayout\fP"
.br
.ti -1c
.RI "class \fBstring\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
