.TH "com.openvision.androidgesture.CreateGestureActivity" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.openvision.androidgesture.CreateGestureActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGesturesProcessor\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddGesture\fP (View v)"
.br
.ti -1c
.RI "void \fBcancelGesture\fP (View v)"
.br
.ti -1c
.RI "native void \fBaddGesture\fP (ArrayList< Float > location, ArrayList< Long > time, String name)"
.br
.ti -1c
.RI "native void \fBsetDirectory\fP (String name)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonSaveInstanceState\fP (Bundle outState)"
.br
.ti -1c
.RI "void \fBonRestoreInstanceState\fP (Bundle savedInstanceState)"
.br
.in -1c
.SS "Package Functions"

.in +1c
.ti -1c
.RI "void \fBextractGestureInfo\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
pi19404 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void \fBcom\&.openvision\&.androidgesture\&.CreateGestureActivity\&.addGesture\fP (Viewv)"
.SS "native void \fBcom\&.openvision\&.androidgesture\&.CreateGestureActivity\&.addGesture\fP (ArrayList< Float >location, ArrayList< Long >time, Stringname)"
.SS "void \fBcom\&.openvision\&.androidgesture\&.CreateGestureActivity\&.cancelGesture\fP (Viewv)"
.SS "void \fBcom\&.openvision\&.androidgesture\&.CreateGestureActivity\&.extractGestureInfo\fP ()\fC [package]\fP"
.SS "void \fBcom\&.openvision\&.androidgesture\&.CreateGestureActivity\&.onCreate\fP (BundlesavedInstanceState)\fC [protected]\fP"
.SS "void \fBcom\&.openvision\&.androidgesture\&.CreateGestureActivity\&.onRestoreInstanceState\fP (BundlesavedInstanceState)\fC [protected]\fP"
.SS "void \fBcom\&.openvision\&.androidgesture\&.CreateGestureActivity\&.onSaveInstanceState\fP (BundleoutState)\fC [protected]\fP"
.SS "native void \fBcom\&.openvision\&.androidgesture\&.CreateGestureActivity\&.setDirectory\fP (Stringname)"

.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
