.TH "com.openvision.androidgesture.OpenVisionGestureA" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.openvision.androidgesture.OpenVisionGestureA \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddGesture\fP (View v)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonActivityResult\fP (int requestCode, int resultCode, Intent data)"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "GestureLibrary \fBmLibrary\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void \fBcom\&.openvision\&.androidgesture\&.OpenVisionGestureA\&.addGesture\fP (Viewv)"
.SS "void \fBcom\&.openvision\&.androidgesture\&.OpenVisionGestureA\&.onActivityResult\fP (intrequestCode, intresultCode, Intentdata)\fC [protected]\fP"
.SS "void \fBcom\&.openvision\&.androidgesture\&.OpenVisionGestureA\&.onCreate\fP (BundlesavedInstanceState)\fC [protected]\fP"
.SH "Member Data Documentation"
.PP 
.SS "GestureLibrary \fBcom\&.openvision\&.androidgesture\&.OpenVisionGestureA\&.mLibrary\fP\fC [package]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
