.TH "jni/ImgApp/GesturePoint.hpp" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/ImgApp/GesturePoint.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Common/OpenCVCommon\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGesturePoint\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
