.TH "GesturePoint" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GesturePoint \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GesturePoint\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBgetTime\fP ()"
.br
.ti -1c
.RI "Point2f \fBgetPosition\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Point2f \fBposition\fP"
.br
.ti -1c
.RI "double \fBtime\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Point2f \fBGesturePoint::getPosition\fP ()"
.SS "double \fBGesturePoint::getTime\fP ()"
.SH "Member Data Documentation"
.PP 
.SS "Point2f \fBGesturePoint::position\fP"
.SS "double \fBGesturePoint::time\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
