.TH "obj/local/armeabi-v7a/objs/OpenVision/OpenVision.o.d" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
obj/local/armeabi-v7a/objs/OpenVision/OpenVision.o.d \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
