.TH "gen/com/openvision/androidgesture/R.java" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gen/com/openvision/androidgesture/R.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.openvision\&.androidgesture\&.R\fP"
.br
.ti -1c
.RI "class \fBcom\&.openvision\&.androidgesture\&.R\&.attr\fP"
.br
.ti -1c
.RI "class \fBcom\&.openvision\&.androidgesture\&.R\&.color\fP"
.br
.ti -1c
.RI "class \fBcom\&.openvision\&.androidgesture\&.R\&.dimen\fP"
.br
.ti -1c
.RI "class \fBcom\&.openvision\&.androidgesture\&.R\&.drawable\fP"
.br
.ti -1c
.RI "class \fBcom\&.openvision\&.androidgesture\&.R\&.id\fP"
.br
.ti -1c
.RI "class \fBcom\&.openvision\&.androidgesture\&.R\&.layout\fP"
.br
.ti -1c
.RI "class \fBcom\&.openvision\&.androidgesture\&.R\&.string\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcom\&.openvision\&.androidgesture\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
