.TH "UniStrokeGestureRecognizer" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniStrokeGestureRecognizer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UniStrokeGestureRecognizer\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsave\fP (string name, vector< \fBGesturePoint\fP > points)"
.br
.ti -1c
.RI "void \fBload\fP (string dirname)"
.br
.ti -1c
.RI "void \fBsetPath\fP (string name)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void \fBUniStrokeGestureRecognizer::load\fP (stringdirname)"
.SS "void \fBUniStrokeGestureRecognizer::save\fP (stringname, vector< \fBGesturePoint\fP >points)"
.SS "void \fBUniStrokeGestureRecognizer::setPath\fP (stringname)"

.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
