.TH "jni/ImgApp/UniStrokeGesture.cpp" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jni/ImgApp/UniStrokeGesture.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'ImgApp/UniStrokeGesture\&.hpp'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
