.TH "UniStrokeGesture" 3 "Wed Aug 20 2014" "Version 0.0.1" "AndroidGesture" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UniStrokeGesture \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <UniStrokeGesture\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "vector< vector< \fBGesturePoint\fP > > \fB_gesturePoint\fP"
.br
.ti -1c
.RI "string \fB_name\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "vector<vector<\fBGesturePoint\fP> > \fBUniStrokeGesture::_gesturePoint\fP"
.SS "string \fBUniStrokeGesture::_name\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for AndroidGesture from the source code\&.
